# Generated by Django 4.2.11 on 2024-03-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_pytorchs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='clothes_classification',
        ),
    ]
